# dev 설정 파일
spring:
  config:
    activate:
      on-profile: dev
  # jpa 관련 설정
  jpa:
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: none
  # schema.sql, data.sql 사용 여부
  sql:
    init:
      mode: never

# 로깅 관련
logging:
  level:
    root: debug
    org.springframework.jdbc.core.JdbcTemplate: debug