# local 설정 파일
spring:
  config:
    activate:
      on-profile: local
  # jpa 관련 설정
  jpa:
    output:
      ansi:
        enabled: always
    hibernate:
      ddl-auto: create
  # schema.sql, data.sql 사용 여부
  sql:
    init:
      mode: always

# 로깅 관련
logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: info