# local 설정 파일
spring:
  # jpa 관련 설정
  jpa:
    output:
      ansi:
        enabled: always
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
  # schema.sql, data.sql 사용 여부
  sql:
    init:
      mode: always
  # postgreSQL local 설정
  datasource:
    url: jdbc:postgresql://localhost:5434/pickly_test
    username: postgres
    password:

# 로깅 관련
logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: info

# 서버 관련
pickly:
  enabled:
    access: true

# p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: true
