# dev 설정 파일
spring:
  # .env파일 이용 여부
  config:
    import:
      - optional:file:.env-dev[.properties]
  # jpa 관련 설정
  jpa:
    output:
      ansi:
        enabled: always
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    database: postgresql
    hibernate:
      ddl-auto: none
  # schema.sql, data.sql 사용 여부
  sql:
    init:
      mode: never
  # postgreSQL local 설정
  datasource:
    url: jdbc:postgresql://localhost:5450/pickly
    username: postgres
    password: postgres

# 로깅 관련
logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: info

# 서버 관련
pickly:
  enabled:
    access: true

# p6spy
decorator:
  datasource:
    p6spy:
      enable-logging: false