# local 설정 파일
spring:
  # jpa 관련 설정
  jpa:
    output:
      ansi:
        enabled: always
    database: postgresql
    properties:
      hibernate:
        format_sql: true
  # schema.sql, data.sql 사용 여부
  sql:
    init:
      mode: always
  # postgreSQL local 설정
  datasource:
    url: jdbc:postgresql://${db.hostname}:${db.port}/${db.dbname}
    username: ${db.username}
    password: ${db.password}

# 로깅 관련
logging:
  level:
    root: info
    org.springframework.jdbc.core.JdbcTemplate: info