global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-actuator-prometheus'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['app:8080']