FROM adoptopenjdk/openjdk15

ARG JAR_FILE=build/libs/*.jar
COPY ${JAR_FILE} pickly-service-1.0-SNAPSHOT.jar

EXPOSE 8080

CMD java \
        -Xms1535m \
        -Xmx1535m \
        -Dfile.encoding=UTF-8 \
        -DlogAppender=STDOUT \
        -Dspring.profiles.active=prod \
        -Duser.timezone=Asia/Seoul \
        -jar pickly-service-1.0-SNAPSHOT.jar
