name: CI

on: [pull_request]

permissions:
  pull-requests: write

jobs:
  checkstyle:
    name: runner / checkstyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: dbelyaev/action-checkstyle@v0.5.1
        with:
          checkstyle_config: google_checks.xml
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          level: error
